spring.mail.host: smtp.exmail.qq.com
spring.mail.port: 465
spring.mail.protocol: smtp
spring.mail.default-encoding: UTF-8
spring.mail.properties.mail.smtp.auth: false
spring.mail.properties.mail.smtp.ssl.enable: true
spring.mail.properties.mail.smtp.timeout: 25000

spring.time.flag : off
logging.level.com: DEBUG

#tomcat:
#  jdbc:
#    poll:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/test
#      username: root
#      password: root

security.basic.enabled : false

server:
  port: 8080
  context-path:
eureka.client.service-url.defaultZone: http://admin:123456@localhost:8761/eureka/
spring.application.name: spring-mail

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mail?characterEncoding=utf8&useSSL=false
      username: root
      password: 1234
    mvc:
     favicon:
      enabled: false  
spring.redis.host: 127.0.0.1
spring.redis.port: 6379  
#spring.redis.password  
spring.redis.database: 1  
spring.redis.pool.max-active: 8  
spring.redis.pool.max-wait: -1  
spring.redis.pool.max-idle: 500  
spring.redis.pool.min-idle: 0  
